<?php

use Step\Acceptance\User;

class SeedCest extends BaseCest
{
	/**
	 * @param User $I
	 *
	 * @throws Exception
	 */
	public function _after( User $I ) {
//		parent::_after( $I ); // TODO: Change the autogenerated stub
	}


	// tests
    public function defaultTest(UnitTester $I)
    {

    }
}
